export const LANG = {
    "en-US": {
        Home: "Home",
        NewsList: "News List",
        Form: "Form",
        UpdatedAt: "Updated at",
        Headlines: "Headlines",
        newsName: "Name",
        newsDescription: "Short description",
        newsUrl: "url",
        imageUrl: "Image url",
    },
    "es-ES": {
        Home: "Casa",
        NewsList: "Nuevas Lista",
        Form: "Forma",
        UpdatedAt: "Updatado a las",
        Headlines: "Cabezalíneas",
        newsName: "Titular",
        newsDescription: "Descripción corta",
        newsUrl: "url",
        imageUrl: "Url de la imagen",
    },
    "fr-FR": {
        Home: "HomeFR",
        NewsList: "News List FR",
        Form: "FormFR",
        UpdatedAt: "Updated atFR",
        Headlines: "HeadlinesFR",
        newsName: "NameFR",
        newsDescription: "Short descriptionFR",
        newsUrl: "urlFR",
        imageUrl: "Image urlFR",
    },
    "de-DE": {
        Home: "HomeDE",
        NewsList: "News List DE",
        Form: "FormDE",
        UpdatedAt: "Updated atDE",
        Headlines: "HeadlinesDE",
        newsName: "NameFR",
        newsDescription: "Short descriptionFR",
        newsUrl: "urlFR",
        imageUrl: "Image urlFR",
    },
}