export const LANG = {
    "en-US": {
        Home: "Home",
        NewsList: "News List",
        Form: "Form",
        UpdatedAt: "Updated at",
        Headlines: "Headlines",
        newsName: "Name",
        newsDescription: "Short description",
        newsUrl: "url",
        imageUrl: "Image url",
        sendForm: "Send",
        readMore: "Read more",
    },
    "es-ES": {
        Home: "Casa",
        NewsList: "Nuevas Lista",
        Form: "Forma",
        UpdatedAt: "Updatado a las",
        Headlines: "Cabezalíneas",
        newsName: "Titular",
        newsDescription: "Descripción corta",
        newsUrl: "url",
        imageUrl: "Url de la imagen",
        sendForm: "Enviar",
        readMore: "Leer más",
    },
    "fr-FR": {
        Home: "Home, pero en francés",
        NewsList: "News List, pero en francés",
        Form: "Form, pero en francés",
        UpdatedAt: "Updated at, pero en francés",
        Headlines: "Headlines, pero en francés",
        newsName: "Name, pero en francés",
        newsDescription: "Short description, pero en francés",
        newsUrl: "url, pero en francés",
        imageUrl: "Image url, pero en francés",
        sendForm: "Send, pero en francés",
        readMore: "Read more, pero en francés",
    },
}